services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mewthedev/linky-dev:latest
    container_name: linky-api-dev
    ports:
      - "${PORT:-7270}:${PORT:-7270}"
    environment:
      NODE_ENV: development
      JOB_WORKER_CONCURRENCY: 4
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT:-7270}/healthz"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - linky-network-dev
    env_file:
      - .env

networks:
  linky-network-dev:
    driver: bridge
