packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - "@clerk/shared"
  - esbuild
  - msw
  - protobufjs
  - sharp
  - supabase
  - unrs-resolver

catalog:
  "@types/node": ^25.3.1
  typescript: ^5.9.3
