packages:
  - apps/web
  - packages/*
  - e2e/playwright

allowBuilds:
  '@clerk/shared': true
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  msw: true
  sharp: true
  unrs-resolver: true

catalog:
  '@types/node': ^25.9.1
  eslint: ^9.39.4
  react: ^19.2.5
  socket.io-client: ^4.8.3
  typescript: ^5.9.3
  zod: 4.4.3

overrides:
  zod: 4.4.3

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@swc/core'
  - msw
  - sharp
  - unrs-resolver
