packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^25.3.2
  typescript: ^5.9.3

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@sentry/cli'
  - esbuild
  - msw
  - protobufjs
  - sharp
  - supabase
  - unrs-resolver
