-- Adds AI moderation assist summary storage for user reports.
-- This is non-authoritative metadata generated by Ollama Cloud.

CREATE TABLE IF NOT EXISTS public.report_ai_summaries (
  report_id uuid PRIMARY KEY REFERENCES public.reports(id) ON DELETE CASCADE,
  status varchar(20) NOT NULL DEFAULT 'pending',
  summary text,
  severity varchar(20),
  suggested_action text,
  model text,
  prompt_version text,
  raw_json jsonb,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT check_report_ai_summary_status CHECK (status IN ('pending', 'ready', 'failed')),
  CONSTRAINT check_report_ai_summary_severity CHECK (severity IS NULL OR severity IN ('low', 'medium', 'high', 'critical'))
);

COMMENT ON TABLE public.report_ai_summaries IS
  'AI-generated moderation assist summary for reports (cacheable, non-authoritative).';

COMMENT ON COLUMN public.report_ai_summaries.status IS 'pending | ready | failed';
COMMENT ON COLUMN public.report_ai_summaries.severity IS 'low | medium | high | critical';

