package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"linky-api/src/internal/app/graphql/generated"
	"linky-api/src/internal/app/graphql/gqlx"
	"linky-api/src/internal/infra/aiconfig"
	"linky-api/src/internal/infra/supax"
)

// Reports is the resolver for the reports field.
func (r *adminResolver) Reports(ctx context.Context, obj *generated.Admin, status *string, reporterUserID *string, reportedUserID *string, limit *int, offset *int) (*generated.AdminReportsPage, error) {
	lim := gqlx.IntDefault(limit, 50)
	off := gqlx.IntDefault(offset, 0)
	rows, count, err := supax.ListAdminReports(ctx, gqlx.StrPtr(status), gqlx.StrPtr(reporterUserID), gqlx.StrPtr(reportedUserID), lim, off)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_REPORTS", "failedFetchReports", "Failed to fetch reports", err))
	}
	if rows == nil {
		rows = []supax.ReportRow{}
	}
	data, err := gqlx.ToAny(rows)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	return &generated.AdminReportsPage{
		Data:   data,
		Count:  int(count),
		Limit:  lim,
		Offset: off,
	}, nil
}

// Report is the resolver for the report field.
func (r *adminResolver) Report(ctx context.Context, obj *generated.Admin, id string) (any, error) {
	row, err := supax.GetReport(ctx, id)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_REPORT", "failedFetchReport", "Failed to fetch report", err))
	}
	if row == nil {
		return nil, gqlx.ErrNotFound("REPORT_NOT_FOUND", "reportNotFound", "Report not found")
	}
	return gqlx.ToAny(row)
}

// InterestTags is the resolver for the interestTags field.
func (r *adminResolver) InterestTags(ctx context.Context, obj *generated.Admin, limit *int, offset *int) (*generated.GenericTablePage, error) {
	return r.adminGenericTable(ctx, "interest_tags", limit, offset)
}

// ExpBonuses is the resolver for the expBonuses field.
func (r *adminResolver) ExpBonuses(ctx context.Context, obj *generated.Admin, limit *int, offset *int) (*generated.GenericTablePage, error) {
	return r.adminGenericTable(ctx, "exp_bonuses", limit, offset)
}

// Config is the resolver for the config field.
func (r *adminResolver) Config(ctx context.Context, obj *generated.Admin) (any, error) {
	rows, err := supax.ListAdminConfig(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_ADMIN_CONFIG", "failedFetchAdminConfig", "Failed to fetch admin config", err))
	}
	if rows == nil {
		rows = []supax.AdminConfigRow{}
	}
	for i := range rows {
		rows[i].Value = aiconfig.RedactAdminConfigRow(rows[i].Key, rows[i].Value)
	}
	return gqlx.ToAny(map[string]any{"data": rows})
}

// ConfigByKey is the resolver for the configByKey field.
func (r *adminResolver) ConfigByKey(ctx context.Context, obj *generated.Admin, key string) (any, error) {
	rows, err := supax.ListAdminConfig(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_ADMIN_CONFIG", "failedFetchAdminConfig", "Failed to fetch admin config", err))
	}
	for _, row := range rows {
		if row.Key == key {
			out, err := gqlx.ToAny(row)
			if err != nil {
				return nil, gqlx.AsGraphQLError(err)
			}
			return out, nil
		}
	}
	return nil, gqlx.ErrNotFound("ADMIN_CONFIG_NOT_FOUND", "adminConfigNotFound", "admin config not found")
}

// Broadcasts is the resolver for the broadcasts field.
func (r *adminResolver) Broadcasts(ctx context.Context, obj *generated.Admin, limit *int, offset *int) (any, error) {
	lim := gqlx.IntDefault(limit, 50)
	if lim > 100 {
		lim = 100
	}
	off := gqlx.IntDefault(offset, 0)
	if off < 0 {
		off = 0
	}
	rows, count, err := supax.ListBroadcastHistory(ctx, lim, off)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_BROADCASTS", "failedFetchBroadcasts", "Failed to fetch broadcasts", err))
	}
	if rows == nil {
		rows = []supax.BroadcastHistoryRow{}
	}
	totalPages := int64(0)
	if lim > 0 {
		totalPages = (count + int64(lim) - 1) / int64(lim)
	}
	return gqlx.ToAny(map[string]any{
		"data": rows,
		"pagination": map[string]any{
			"limit":      lim,
			"offset":     off,
			"total":      count,
			"totalPages": totalPages,
		},
	})
}

// Embeddings is the resolver for the embeddings field.
func (r *adminResolver) Embeddings(ctx context.Context, obj *generated.Admin, limit *int, offset *int) (*generated.GenericTablePage, error) {
	return r.adminGenericTable(ctx, "user_embeddings", limit, offset)
}

// Admin returns generated.AdminResolver implementation.
func (r *Resolver) Admin() generated.AdminResolver { return &adminResolver{r} }

type adminResolver struct{ *Resolver }

func (r *adminResolver) adminGenericTable(ctx context.Context, table string, limit *int, offset *int) (*generated.GenericTablePage, error) {
	lim := gqlx.IntDefault(limit, 50)
	off := gqlx.IntDefault(offset, 0)
	rows, count, err := supax.ListGenericTable(ctx, table, lim, off)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_TABLE", "failedFetchTable", "Failed to fetch records", err))
	}
	if rows == nil {
		rows = []map[string]any{}
	}
	data, err := gqlx.ToAny(rows)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	return &generated.GenericTablePage{
		Data:  data,
		Count: int(count),
	}, nil
}
