package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"errors"
	"linky-api/src/internal/app/admin"
	"linky-api/src/internal/app/broadcastai"
	"linky-api/src/internal/app/favorite"
	"linky-api/src/internal/app/graphql/generated"
	"linky-api/src/internal/app/graphql/gqlx"
	reportapp "linky-api/src/internal/app/report"
	"linky-api/src/internal/app/user"
	"linky-api/src/internal/app/videochat"
)

// PatchUser is the resolver for the patchUser field.
func (r *adminMutationResolver) PatchUser(ctx context.Context, obj *generated.AdminMutation, id string, input any) (any, error) {
	body, err := gqlx.ToMap(input)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	row, err := admin.PatchUser(ctx, id, body, true)
	if err != nil {
		if errors.Is(err, admin.ErrCannotAssignSuperadmin) {
			return nil, gqlx.ErrForbidden("CANNOT_ASSIGN_SUPERADMIN", "cannotAssignSuperadmin", "Cannot assign superadmin role")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_UPDATE_USER", "failedUpdateUser", "Failed to update user", err))
	}
	return row, nil
}

// SoftDeleteUser is the resolver for the softDeleteUser field.
func (r *adminMutationResolver) SoftDeleteUser(ctx context.Context, obj *generated.AdminMutation, id string) (*bool, error) {
	if err := admin.SoftDeleteUser(ctx, id); err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_DELETE_USER", "failedDeleteUser", "Failed to delete user", err))
	}
	return gqlx.BoolPtr(true), nil
}

// PatchReport is the resolver for the patchReport field.
func (r *adminMutationResolver) PatchReport(ctx context.Context, obj *generated.AdminMutation, id string, input any) (any, error) {
	body, err := gqlx.ToMap(input)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	row, err := admin.PatchReport(ctx, id, body)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_UPDATE_REPORT", "failedUpdateReport", "Failed to update report", err))
	}
	return row, nil
}

// EnqueueReportAiSummary is the resolver for the enqueueReportAiSummary field.
func (r *adminMutationResolver) EnqueueReportAiSummary(ctx context.Context, obj *generated.AdminMutation, id string) (*generated.AsyncJobResult, error) {
	result, err := admin.EnqueueReportAISummary(ctx, id)
	if err != nil {
		if errors.Is(err, admin.ErrReportIDRequired) {
			return nil, gqlx.ErrBadRequest("REPORT_ID_REQUIRED", "reportIdRequired", "id required")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("REPORT_AI_ENQUEUE_FAIL", "reportAiEnqueueFail", "Failed to enqueue AI summary job", err))
	}
	return toAsyncJobResult(result), nil
}

// RegenerateEmbeddings is the resolver for the regenerateEmbeddings field.
func (r *adminMutationResolver) RegenerateEmbeddings(ctx context.Context, obj *generated.AdminMutation, userIds []string) (*generated.AsyncJobResult, error) {
	result, err := admin.RegenerateEmbeddings(ctx, userIds)
	if err != nil {
		if errors.Is(err, admin.ErrUserIDsRequired) {
			return nil, gqlx.ErrBadRequest("USER_IDS_REQUIRED", "userIdsRequired", "user_ids must be a non-empty array")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_LIST_USERS", "failedListUsers", "Failed to list users", err))
	}
	return toAsyncJobResult(result), nil
}

// SyncEmbeddings is the resolver for the syncEmbeddings field.
func (r *adminMutationResolver) SyncEmbeddings(ctx context.Context, obj *generated.AdminMutation, userIds []string) (*generated.AsyncJobResult, error) {
	result, err := admin.SyncEmbeddings(ctx, userIds)
	if err != nil {
		if errors.Is(err, admin.ErrUserIDsRequired) {
			return nil, gqlx.ErrBadRequest("USER_IDS_REQUIRED", "userIdsRequired", "user_ids must be a non-empty array")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_LIST_USERS", "failedListUsers", "Failed to list users", err))
	}
	return toAsyncJobResult(result), nil
}

// SyncAllEmbeddings is the resolver for the syncAllEmbeddings field.
func (r *adminMutationResolver) SyncAllEmbeddings(ctx context.Context, obj *generated.AdminMutation) (*generated.AsyncJobResult, error) {
	result, err := admin.SyncAllEmbeddings(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_LIST_USERS", "failedListUsers", "Failed to list users", err))
	}
	return toAsyncJobResult(result), nil
}

// CompareEmbeddings is the resolver for the compareEmbeddings field.
func (r *adminMutationResolver) CompareEmbeddings(ctx context.Context, obj *generated.AdminMutation, userIDA string, userIDB string) (any, error) {
	out, err := admin.CompareEmbeddings(ctx, userIDA, userIDB)
	if err != nil {
		if errors.Is(err, admin.ErrUserIDsRequired) {
			return nil, gqlx.ErrBadRequest("USER_IDS_REQUIRED", "userIdsRequired", "user_id_a and user_id_b are required")
		}
		if errors.Is(err, admin.ErrEmbeddingMissing) {
			return nil, gqlx.ErrNotFound("EMBEDDING_MISSING", "embeddingMissing", "Embedding not found for one or both users")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_EMBEDDINGS", "failedFetchEmbeddings", "Failed to fetch embeddings", err))
	}
	return out, nil
}

// FindSimilarEmbeddings is the resolver for the findSimilarEmbeddings field.
func (r *adminMutationResolver) FindSimilarEmbeddings(ctx context.Context, obj *generated.AdminMutation, userID string, limit *int, threshold *float64) (any, error) {
	out, err := admin.FindSimilarEmbeddings(ctx, userID, gqlx.IntDefault(limit, 25), gqlx.FloatDefault(threshold, 0.5))
	if err != nil {
		if errors.Is(err, admin.ErrUserIDRequired) {
			return nil, gqlx.ErrBadRequest("USER_ID_REQUIRED", "userIdRequired", "user_id is required")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FIND_SIMILAR", "failedFindSimilar", "Failed to find similar users", err))
	}
	return out, nil
}

// CreateBroadcast is the resolver for the createBroadcast field.
func (r *adminMutationResolver) CreateBroadcast(ctx context.Context, obj *generated.AdminMutation, message string, title *string, deliveryMode *string, url *string) (any, error) {
	out, err := admin.CreateBroadcast(ctx, admin.CreateBroadcastInput{
		Message:      message,
		Title:        gqlx.StrPtr(title),
		DeliveryMode: gqlx.StrPtr(deliveryMode),
		URL:          gqlx.StrPtr(url),
		CreatorClerk: gqlx.ClerkUserID(ctx),
	})
	if err != nil {
		if errors.Is(err, admin.ErrBroadcastMessageRequired) {
			return nil, gqlx.ErrBadRequest("BROADCAST_MESSAGE_REQUIRED", "broadcastMessageRequired", "message is required")
		}
		if err.Error() == "user not found in database" {
			return nil, gqlx.ErrNotFound("USER_NOT_IN_DB", "userNotInDatabase", "User not found in database")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_CREATE_BROADCAST", "failedCreateBroadcast", "Failed to create broadcast", err))
	}
	return out, nil
}

// GenerateBroadcastAi is the resolver for the generateBroadcastAi field.
func (r *adminMutationResolver) GenerateBroadcastAi(ctx context.Context, obj *generated.AdminMutation, audience *string, keyPoints *string) (any, error) {
	out, err := admin.GenerateBroadcastAI(ctx, admin.GenerateBroadcastAIInput{
		Audience:        gqlx.StrPtr(audience),
		KeyPoints:       gqlx.StrPtr(keyPoints),
		CreatedByUserID: gqlx.ClerkUserID(ctx),
	})
	if err != nil {
		if errors.Is(err, broadcastai.ErrInProgress) {
			return nil, gqlx.ErrTooManyRequests("BROADCAST_AI_BUSY", "broadcastAiBusy", "Broadcast AI generation already in progress. Please retry shortly.", nil)
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("BROADCAST_AI_FAILED", "broadcastAiFailed", err.Error(), err))
	}
	return out, nil
}

// UpdateAiConfig is the resolver for the updateAiConfig field.
func (r *adminMutationResolver) UpdateAiConfig(ctx context.Context, obj *generated.AdminMutation, value any) (any, error) {
	body, err := gqlx.ToMap(value)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	out, err := admin.PutAIConfig(ctx, body)
	if err != nil {
		if errors.Is(err, admin.ErrAIConfigValueRequired) {
			return nil, gqlx.ErrBadRequest("AI_CONFIG_VALUE_REQUIRED", "aiConfigValueRequired", "value is required")
		}
		if errors.Is(err, admin.ErrAIConfigInvalid) {
			return nil, gqlx.ErrBadRequest("AI_CONFIG_INVALID", "aiConfigInvalid", "Invalid AI config JSON")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_UPSERT_AI_CONFIG", "failedUpsertAiConfig", "Failed to save AI config", err))
	}
	return out, nil
}

// Viewer is the resolver for the viewer field.
func (r *mutationResolver) Viewer(ctx context.Context) (*generated.ViewerMutation, error) {
	if err := gqlx.RequireClerk(ctx); err != nil {
		return nil, err
	}
	return &generated.ViewerMutation{}, nil
}

// Admin is the resolver for the admin field.
func (r *mutationResolver) Admin(ctx context.Context) (*generated.AdminMutation, error) {
	if err := gqlx.RequireAdmin(ctx); err != nil {
		return nil, err
	}
	return &generated.AdminMutation{}, nil
}

// UpdateCountry is the resolver for the updateCountry field.
func (r *viewerMutationResolver) UpdateCountry(ctx context.Context, obj *generated.ViewerMutation, country string) (any, error) {
	if country == "" {
		return nil, gqlx.ErrBadRequest("COUNTRY_REQUIRED", "countryRequiredString", "Country is required and must be a string")
	}
	updated, err := user.UpdateCountry(ctx, gqlx.ClerkUserID(ctx), country)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_UPDATE_COUNTRY", "failedUpdateUserCountry", "Failed to update user country", err))
	}
	if updated == nil {
		return nil, gqlx.ErrNotFound("USER_NOT_IN_DB", "userNotInDatabase", "User not found in database")
	}
	return updated, nil
}

// UpdateUserDetails is the resolver for the updateUserDetails field.
func (r *viewerMutationResolver) UpdateUserDetails(ctx context.Context, obj *generated.ViewerMutation, input any) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	body, err := gqlx.ToMap(input)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	out, err := user.UpsertDetails(ctx, uid, body)
	if err != nil {
		return nil, gqlx.MapDetailsValidation(err)
	}
	return out, nil
}

// AddInterestTags is the resolver for the addInterestTags field.
func (r *viewerMutationResolver) AddInterestTags(ctx context.Context, obj *generated.ViewerMutation, tagIds []string) (any, error) {
	return r.mutateInterestTags(ctx, "add", tagIds)
}

// RemoveInterestTags is the resolver for the removeInterestTags field.
func (r *viewerMutationResolver) RemoveInterestTags(ctx context.Context, obj *generated.ViewerMutation, tagIds []string) (any, error) {
	return r.mutateInterestTags(ctx, "remove", tagIds)
}

// ReplaceInterestTags is the resolver for the replaceInterestTags field.
func (r *viewerMutationResolver) ReplaceInterestTags(ctx context.Context, obj *generated.ViewerMutation, tagIds []string) (any, error) {
	return r.mutateInterestTags(ctx, "replace", tagIds)
}

// ClearInterestTags is the resolver for the clearInterestTags field.
func (r *viewerMutationResolver) ClearInterestTags(ctx context.Context, obj *generated.ViewerMutation) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	out, err := user.ClearInterestTags(ctx, uid)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_CLEAR_TAGS", "failedClearInterestTags", "Failed to clear interest tags", err))
	}
	return out, nil
}

// AddFavorite is the resolver for the addFavorite field.
func (r *viewerMutationResolver) AddFavorite(ctx context.Context, obj *generated.ViewerMutation, favoriteUserID string) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	row, err := favorite.Add(ctx, uid, favoriteUserID)
	if err != nil {
		var limitErr *favorite.DailyLimitError
		if errors.As(err, &limitErr) {
			return nil, gqlx.ErrTooManyRequests("DAILY_FAVORITE_LIMIT", "dailyFavoriteLimitReached", "Daily favorite limit reached", map[string]any{
				"current": limitErr.Current,
				"limit":   limitErr.Limit,
			})
		}
		if errors.Is(err, favorite.ErrFavoriteUserIDReq) {
			return nil, gqlx.ErrBadRequest("FAVORITE_USER_ID_REQUIRED", "favoriteUserIdRequired", "favorite_user_id is required")
		}
		if errors.Is(err, favorite.ErrSelfFavorite) {
			return nil, gqlx.ErrBadRequest("CANNOT_FAVORITE_SELF", "cannotFavoriteYourself", "Cannot favorite yourself")
		}
		if errors.Is(err, favorite.ErrAlreadyExists) {
			return nil, gqlx.ErrConflict("ALREADY_IN_FAVORITES", "alreadyInFavorites", "User is already in favorites")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_ADD_FAVORITE", "failedAddFavorite", "Failed to add favorite", err))
	}
	return row, nil
}

// RemoveFavorite is the resolver for the removeFavorite field.
func (r *viewerMutationResolver) RemoveFavorite(ctx context.Context, obj *generated.ViewerMutation, favoriteUserID string) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	refunded, err := favorite.Remove(ctx, uid, favoriteUserID)
	if err != nil {
		if errors.Is(err, favorite.ErrFavoriteUserIDReq) {
			return nil, gqlx.ErrBadRequest("FAVORITE_USER_ID_REQUIRED", "favoriteUserIdRequired", "favorite_user_id is required")
		}
		if errors.Is(err, favorite.ErrNotFound) {
			return nil, gqlx.ErrNotFound("FAVORITE_NOT_FOUND", "favoriteNotFound", "Favorite not found")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_REMOVE_FAVORITE", "failedRemoveFavorite", "Failed to remove favorite", err))
	}
	return map[string]any{"refunded": refunded}, nil
}

// CreateBlock is the resolver for the createBlock field.
func (r *viewerMutationResolver) CreateBlock(ctx context.Context, obj *generated.ViewerMutation, blockedUserID string) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	if blockedUserID == "" {
		return nil, gqlx.ErrBadRequest("BLOCKED_USER_ID_REQUIRED", "blockedUserIdRequired", "blocked_user_id is required")
	}
	row, err := user.CreateBlock(ctx, uid, blockedUserID)
	if err != nil {
		if errors.Is(err, user.ErrBlockSelf) || errors.Is(err, user.ErrAlreadyBlocked) {
			return nil, gqlx.ErrBadRequest("BLOCK_VALIDATION", "blockValidation", err.Error())
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_BLOCK_USER", "failedBlockUser", "Failed to block user", err))
	}
	return row, nil
}

// DeleteBlock is the resolver for the deleteBlock field.
func (r *viewerMutationResolver) DeleteBlock(ctx context.Context, obj *generated.ViewerMutation, blockedUserID string) (*bool, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	if blockedUserID == "" {
		return nil, gqlx.ErrBadRequest("BLOCKED_USER_ID_REQUIRED", "blockedUserIdRequired", "blocked_user_id is required")
	}
	if err := user.DeleteBlock(ctx, uid, blockedUserID); err != nil {
		if errors.Is(err, user.ErrNotBlocked) {
			return nil, gqlx.ErrNotFound("NOT_BLOCKED", "notBlocked", "User is not blocked")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_UNBLOCK_USER", "failedUnblockUser", "Failed to unblock user", err))
	}
	return gqlx.BoolPtr(true), nil
}

// CreateReport is the resolver for the createReport field.
func (r *viewerMutationResolver) CreateReport(ctx context.Context, obj *generated.ViewerMutation, reportedUserID string, reason string, description *string, metadata any) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	meta, err := gqlx.ToMetadataMap(metadata)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	desc := ""
	if description != nil {
		desc = *description
	}
	row, err := reportapp.Create(ctx, uid, reportapp.CreateInput{
		ReportedUserID: reportedUserID,
		Reason:         reason,
		Description:    desc,
		Metadata:       meta,
	})
	if err != nil {
		if errors.Is(err, reportapp.ErrReportTargetRequired) {
			return nil, gqlx.ErrBadRequest("REPORT_TARGET_REQUIRED", "reportTargetRequired", "reported_user_id is required")
		}
		if errors.Is(err, reportapp.ErrReportReasonRequired) {
			return nil, gqlx.ErrBadRequest("REPORT_REASON_REQUIRED", "reportReasonRequired", "reason is required")
		}
		if errors.Is(err, reportapp.ErrReportSelf) {
			return nil, gqlx.ErrBadRequest("REPORT_SELF", "reportSelf", "Cannot report yourself")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_CREATE_REPORT", "failedCreateReport", "Failed to create report", err))
	}
	return row, nil
}

// CreateCallHistory is the resolver for the createCallHistory field.
func (r *viewerMutationResolver) CreateCallHistory(ctx context.Context, obj *generated.ViewerMutation, input generated.CreateCallHistoryInput) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	var startedAt, endedAt string
	if input.StartedAt != nil {
		startedAt = *input.StartedAt
	}
	if input.EndedAt != nil {
		endedAt = *input.EndedAt
	}
	row, err := videochat.CreateCallHistory(ctx, uid, videochat.CreateCallHistoryInput{
		CallerID:        input.CallerID,
		CalleeID:        input.CalleeID,
		StartedAt:       startedAt,
		EndedAt:         endedAt,
		DurationSeconds: input.DurationSeconds,
	})
	if err != nil {
		if errors.Is(err, videochat.ErrCallerCalleeRequired) {
			return nil, gqlx.ErrBadRequest("CALLER_CALLEE_REQUIRED", "callerCalleeRequired", "caller_id and callee_id are required")
		}
		if errors.Is(err, videochat.ErrCallHistorySelfOnly) {
			return nil, gqlx.ErrForbidden("CALL_HISTORY_SELF_ONLY", "callHistorySelfOnly", "You can only create call history records for yourself")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_CREATE_CALL_HISTORY", "failedCreateCallHistory", "Failed to create call history", err))
	}
	return row, nil
}

// AdminMutation returns generated.AdminMutationResolver implementation.
func (r *Resolver) AdminMutation() generated.AdminMutationResolver { return &adminMutationResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// ViewerMutation returns generated.ViewerMutationResolver implementation.
func (r *Resolver) ViewerMutation() generated.ViewerMutationResolver {
	return &viewerMutationResolver{r}
}

type adminMutationResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type viewerMutationResolver struct{ *Resolver }
