package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"linky-api/src/internal/app/graphql/generated"
	"linky-api/src/internal/app/graphql/gqlx"
	"linky-api/src/internal/infra/supax"
)

func (r *queryResolver) Viewer(ctx context.Context) (*generated.Viewer, error) {
	if err := gqlx.RequireClerk(ctx); err != nil {
		return nil, err
	}
	return &generated.Viewer{}, nil
}

func (r *queryResolver) InterestTags(ctx context.Context, category *string, search *string, limit *int, offset *int) (*generated.InterestTagPage, error) {
	if err := gqlx.RequireClerk(ctx); err != nil {
		return nil, err
	}
	lim := gqlx.IntDefault(limit, 100)
	if lim > 200 {
		lim = 200
	}
	off := gqlx.IntDefault(offset, 0)
	rows, count, err := supax.GetInterestTags(ctx, gqlx.StrPtr(category), gqlx.StrPtr(search), true, lim, off)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_INTEREST_TAGS", "failedFetchInterestTags", "Failed to fetch interest tags", err))
	}
	if rows == nil {
		rows = []supax.InterestTagRow{}
	}
	totalPages := int64(0)
	if lim > 0 {
		totalPages = (count + int64(lim) - 1) / int64(lim)
	}
	data, err := gqlx.ToAny(rows)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	pagination, err := gqlx.ToAny(map[string]any{
		"limit":      lim,
		"offset":     off,
		"total":      count,
		"totalPages": totalPages,
	})
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	return &generated.InterestTagPage{
		Data:       data,
		Pagination: pagination,
	}, nil
}

func (r *queryResolver) InterestTag(ctx context.Context, id string) (any, error) {
	if err := gqlx.RequireClerk(ctx); err != nil {
		return nil, err
	}
	row, err := supax.GetInterestTagByID(ctx, id)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_INTEREST_TAG", "failedFetchInterestTag", "Failed to fetch interest tag", err))
	}
	if row == nil || !row.IsActive {
		return nil, gqlx.ErrNotFound("INTEREST_TAG_NOT_FOUND", "interestTagNotFound", "Interest tag not found")
	}
	return gqlx.ToAny(row)
}

func (r *queryResolver) Admin(ctx context.Context) (*generated.Admin, error) {
	if err := gqlx.RequireAdmin(ctx); err != nil {
		return nil, err
	}
	return &generated.Admin{}, nil
}

func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
