package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"errors"
	"linky-api/src/internal/app/favorite"
	"linky-api/src/internal/app/graphql/generated"
	"linky-api/src/internal/app/graphql/gqlx"
	"linky-api/src/internal/app/user"
	"linky-api/src/internal/app/videochat"
	"linky-api/src/internal/infra/supax"
)

// Me is the resolver for the me field.
func (r *viewerResolver) Me(ctx context.Context, obj *generated.Viewer) (any, error) {
	row, err := user.GetMe(ctx, gqlx.ClerkUserID(ctx), gqlx.CFCountry(ctx))
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_USER_DATA", "failedFetchUserData", "Failed to fetch user data", err))
	}
	if row == nil {
		return nil, gqlx.ErrNotFound("USER_NOT_IN_DB", "userNotInDatabase", "User not found in database")
	}
	return gqlx.ToAny(row)
}

// Details is the resolver for the details field.
func (r *viewerResolver) Details(ctx context.Context, obj *generated.Viewer) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	details, err := supax.GetUserDetailsWithTags(ctx, uid)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_DETAILS", "failedFetchUserDetails", "Failed to fetch user details", err))
	}
	if details == nil {
		return nil, gqlx.ErrNotFound("USER_DETAILS_NOT_FOUND", "userDetailsNotFound", "User details not found")
	}
	return details, nil
}

// Settings is the resolver for the settings field.
func (r *viewerResolver) Settings(ctx context.Context, obj *generated.Viewer) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	settings, err := supax.GetUserSettings(ctx, uid)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_SETTINGS", "failedFetchUserSettings", "Failed to fetch user settings", err))
	}
	if settings == nil {
		return nil, gqlx.ErrNotFound("USER_SETTINGS_NOT_FOUND", "userSettingsNotFound", "User settings not found")
	}
	return settings, nil
}

// Profile is the resolver for the profile field.
func (r *viewerResolver) Profile(ctx context.Context, obj *generated.Viewer) (any, error) {
	clerkID := gqlx.ClerkUserID(ctx)
	profile, err := supax.GetUserProfileAggregate(ctx, clerkID)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_PROFILE", "failedFetchUserProfile", "Failed to fetch user profile", err))
	}
	if profile == nil {
		return nil, gqlx.ErrNotFound("USER_NOT_IN_DB", "userNotInDatabase", "User not found in database")
	}
	return profile, nil
}

// Level is the resolver for the level field.
func (r *viewerResolver) Level(ctx context.Context, obj *generated.Viewer) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	data, err := user.GetUserLevelData(ctx, uid)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_LEVEL", "failedFetchUserLevel", "Failed to fetch user level", err))
	}
	if data == nil {
		return nil, gqlx.ErrNotFound("USER_LEVEL_NOT_FOUND", "userLevelNotFound", "User level data not found")
	}
	return gqlx.ToAny(data)
}

// Streak is the resolver for the streak field.
func (r *viewerResolver) Streak(ctx context.Context, obj *generated.Viewer) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	data, err := user.GetUserStreakData(ctx, uid)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_STREAK", "failedFetchUserStreak", "Failed to fetch user streak", err))
	}
	if data == nil {
		return nil, gqlx.ErrNotFound("USER_STREAK_NOT_FOUND", "userStreakNotFound", "User streak data not found")
	}
	return gqlx.ToAny(data)
}

// Progress is the resolver for the progress field.
func (r *viewerResolver) Progress(ctx context.Context, obj *generated.Viewer) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	tz := user.ResolveTimezone(ctx, uid, nil)
	insights, err := user.GetProgressInsights(ctx, uid, tz)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_PROGRESS", "failedFetchUserProgress", "Failed to fetch user progress", err))
	}
	if insights == nil {
		return nil, gqlx.ErrNotFound("USER_PROGRESS_NOT_FOUND", "userProgressNotFound", "User progress data not found")
	}
	return gqlx.ToAny(insights)
}

// Notifications is the resolver for the notifications field.
func (r *viewerResolver) Notifications(ctx context.Context, obj *generated.Viewer, limit *int, offset *int, unreadOnly *bool) (*generated.NotificationsPage, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	lim := gqlx.IntDefault(limit, 20)
	off := gqlx.IntDefault(offset, 0)
	unread := unreadOnly != nil && *unreadOnly
	rows, err := user.ListNotifications(ctx, uid, lim, off, unread)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_NOTIFICATIONS", "failedFetchNotifications", "Failed to fetch notifications", err))
	}
	items, err := gqlx.ToAny(rows)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	return &generated.NotificationsPage{Notifications: items}, nil
}

// UnreadNotificationCount is the resolver for the unreadNotificationCount field.
func (r *viewerResolver) UnreadNotificationCount(ctx context.Context, obj *generated.Viewer) (int, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return 0, gqlx.AsGraphQLError(err)
	}
	count, err := user.UnreadNotificationCount(ctx, uid)
	if err != nil {
		return 0, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_UNREAD", "failedFetchUnreadCount", "Failed to fetch unread count", err))
	}
	return int(count), nil
}

// CallHistory is the resolver for the callHistory field.
func (r *viewerResolver) CallHistory(ctx context.Context, obj *generated.Viewer, limit *int, offset *int) (*generated.CallHistoryPage, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	lim := gqlx.IntDefault(limit, 50)
	off := gqlx.IntDefault(offset, 0)
	rows, count, err := videochat.ListCallHistory(ctx, uid, lim, off)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_CALL_HISTORY", "failedFetchCallHistory", "Failed to fetch call history", err))
	}
	data, err := gqlx.ToAny(rows)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	return &generated.CallHistoryPage{
		Data:   data,
		Count:  int(count),
		Limit:  lim,
		Offset: off,
	}, nil
}

// CallHistoryItem is the resolver for the callHistoryItem field.
func (r *viewerResolver) CallHistoryItem(ctx context.Context, obj *generated.Viewer, id string) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	row, err := videochat.GetCallHistoryItem(ctx, uid, id)
	if err != nil {
		if errors.Is(err, videochat.ErrCallHistoryForbidden) {
			return nil, gqlx.ErrForbidden("NO_ACCESS_CALL_HISTORY", "noAccessCallHistory", "You do not have access to this call history record")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_CALL_HISTORY", "failedFetchCallHistory", "Failed to fetch call history", err))
	}
	if row == nil {
		return nil, gqlx.ErrNotFound("CALL_HISTORY_NOT_FOUND", "callHistoryNotFound", "Call history record not found")
	}
	return gqlx.ToAny(row)
}

// Reports is the resolver for the reports field.
func (r *viewerResolver) Reports(ctx context.Context, obj *generated.Viewer, limit *int, offset *int) (*generated.ReportsPage, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	lim := gqlx.IntDefault(limit, 20)
	off := gqlx.IntDefault(offset, 0)
	rows, count, err := supax.ListReports(ctx, uid, lim, off)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_REPORTS", "failedFetchReports", "Failed to fetch reports", err))
	}
	if rows == nil {
		rows = []supax.ReportRow{}
	}
	data, err := gqlx.ToAny(rows)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	return &generated.ReportsPage{
		Data:  data,
		Count: int(count),
	}, nil
}

// StreakCalendar is the resolver for the streakCalendar field.
func (r *viewerResolver) StreakCalendar(ctx context.Context, obj *generated.Viewer, year int, month int) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	out, err := user.StreakCalendar(ctx, uid, year, month)
	if err != nil {
		if errors.Is(err, user.ErrYearRequired) {
			return nil, gqlx.ErrBadRequest("YEAR_QUERY_REQUIRED", "yearQueryRequired", "Year query parameter is required and must be a number")
		}
		if errors.Is(err, user.ErrMonthRequired) {
			return nil, gqlx.ErrBadRequest("MONTH_QUERY_REQUIRED", "monthQueryRequired", "Month query parameter is required and must be a number")
		}
		if errors.Is(err, user.ErrMonthRange) {
			return nil, gqlx.ErrBadRequest("MONTH_RANGE", "monthBetween1And12", "Month must be between 1 and 12")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_STREAK_CAL", "failedFetchStreakCalendar", "Failed to fetch user streak calendar", err))
	}
	return out, nil
}

// StreakHistory is the resolver for the streakHistory field.
func (r *viewerResolver) StreakHistory(ctx context.Context, obj *generated.Viewer, limit *int, offset *int) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	off := 0
	if offset != nil {
		off = *offset
	}
	out, err := user.StreakHistory(ctx, uid, gqlx.IntDefault(limit, 50), off)
	if err != nil {
		if errors.Is(err, user.ErrStreakLimitRange) {
			return nil, gqlx.ErrBadRequest("STREAK_LIMIT_RANGE", "limitBetween1And100", "Limit must be between 1 and 100")
		}
		if errors.Is(err, user.ErrStreakOffsetNonNeg) {
			return nil, gqlx.ErrBadRequest("STREAK_OFFSET_NONNEG", "offsetNonNegative", "Offset must be a non-negative number")
		}
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_STREAK_HISTORY", "failedFetchStreakHistory", "Failed to fetch user streak history", err))
	}
	return out, nil
}

// Favorites is the resolver for the favorites field.
func (r *viewerResolver) Favorites(ctx context.Context, obj *generated.Viewer) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	out, err := favorite.ListWithStats(ctx, uid)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_FAVORITES", "failedFetchFavorites", "Failed to fetch favorites", err))
	}
	return out, nil
}

// Blocks is the resolver for the blocks field.
func (r *viewerResolver) Blocks(ctx context.Context, obj *generated.Viewer) (any, error) {
	uid, err := gqlx.RequireInternalUser(ctx)
	if err != nil {
		return nil, gqlx.AsGraphQLError(err)
	}
	rows, err := user.ListBlocks(ctx, uid)
	if err != nil {
		return nil, gqlx.AsGraphQLError(gqlx.ErrInternal("FAILED_FETCH_BLOCKED", "failedFetchBlockedUsers", "Failed to fetch blocked users", err))
	}
	return map[string]any{"blocked_users": rows}, nil
}

// Viewer returns generated.ViewerResolver implementation.
func (r *Resolver) Viewer() generated.ViewerResolver { return &viewerResolver{r} }

type viewerResolver struct{ *Resolver }
