import { z } from "zod";

const publicEnvSchema = z
  .object({
    NEXT_PUBLIC_API_URL: z.string().min(1, "NEXT_PUBLIC_API_URL is required"),
    NEXT_PUBLIC_APP_URL: z.string().min(1, "NEXT_PUBLIC_APP_URL is required"),
    NEXT_PUBLIC_OPENPANEL_CLIENT_ID: z
      .string()
      .min(1, "NEXT_PUBLIC_OPENPANEL_CLIENT_ID is required"),
    NEXT_PUBLIC_GIPHY_API_KEY: z
      .string()
      .min(1, "NEXT_PUBLIC_GIPHY_API_KEY is required"),
    NEXT_PUBLIC_ALLOWED_DEV_ORIGINS: z.string().optional().default(""),
    NEXT_PUBLIC_MQTT_CLIENT_URL: z.string().optional(),
    NEXT_PUBLIC_MQTT_CLIENT_PORT: z.string().optional(),
    NEXT_PUBLIC_MQTT_CLIENT_USERNAME: z.string().optional(),
    NEXT_PUBLIC_MQTT_CLIENT_PASSWORD: z.string().optional(),
  })
  .strict();

const raw = {
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_OPENPANEL_CLIENT_ID: process.env.NEXT_PUBLIC_OPENPANEL_CLIENT_ID,
  NEXT_PUBLIC_GIPHY_API_KEY: process.env.NEXT_PUBLIC_GIPHY_API_KEY,
  NEXT_PUBLIC_ALLOWED_DEV_ORIGINS: process.env.NEXT_PUBLIC_ALLOWED_DEV_ORIGINS,
  NEXT_PUBLIC_MQTT_CLIENT_URL: process.env.NEXT_PUBLIC_MQTT_CLIENT_URL,
  NEXT_PUBLIC_MQTT_CLIENT_PORT: process.env.NEXT_PUBLIC_MQTT_CLIENT_PORT,
  NEXT_PUBLIC_MQTT_CLIENT_USERNAME: process.env.NEXT_PUBLIC_MQTT_CLIENT_USERNAME,
  NEXT_PUBLIC_MQTT_CLIENT_PASSWORD: process.env.NEXT_PUBLIC_MQTT_CLIENT_PASSWORD,
};

const parsed = publicEnvSchema.parse(raw);

export const publicEnv = {
  API_URL: parsed.NEXT_PUBLIC_API_URL,
  APP_URL: parsed.NEXT_PUBLIC_APP_URL,
  OPENPANEL_CLIENT_ID: parsed.NEXT_PUBLIC_OPENPANEL_CLIENT_ID,
  GIPHY_API_KEY: parsed.NEXT_PUBLIC_GIPHY_API_KEY,
  ALLOWED_DEV_ORIGINS: parsed.NEXT_PUBLIC_ALLOWED_DEV_ORIGINS,
  MQTT_CLIENT_URL: parsed.NEXT_PUBLIC_MQTT_CLIENT_URL,
  MQTT_CLIENT_PORT: parsed.NEXT_PUBLIC_MQTT_CLIENT_PORT,
  MQTT_CLIENT_USERNAME: parsed.NEXT_PUBLIC_MQTT_CLIENT_USERNAME,
  MQTT_CLIENT_PASSWORD: parsed.NEXT_PUBLIC_MQTT_CLIENT_PASSWORD,
  isDev: process.env.NODE_ENV === "development",
} as const;

export type PublicEnv = typeof publicEnv;
