root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./src/cmd/api"
  delay = 500
  exclude_dir = ["tmp", "bin", "vendor", "node_modules", "migrations"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go"]
  kill_delay = "500ms"
  send_interrupt = true

[log]
  time = false

[misc]
  clean_on_exit = true
